# Site settings
title: Carter Perry Bailey LLP
email: webmaster@cpblaw.com
baseurl: ""
url: "https://www.cpblaw.com"
#url: "https://www.cpblaw.com"

plugins:
  - jekyll-redirect-from

exclude: ['CNAME']
