[build] # default master branch
  publish = "_site/"
  command = "JEKYLL_ENV=production jekyll build"
[context.preview] # 'preview' is the branch name
  publish = "_site/"
  command = "JEKYLL_ENV=preview jekyll build --config _config.yml,_config_preview.yml"
